const seedData = {
  mice: [
    {
      identifier: 3,
      earPunch: "N",
      strain: "strain1",
      sex: "M",
      dateOfBirth: "01/01/24",
      genotype: "genotype1",
      fatherId: 1,
      motherId: 2,
      cageID: 0,
    },
    {
      identifier: 4,
      earPunch: "R",
      strain: "strain1",
      sex: "M",
      dateOfBirth: "01/01/24",
      genotype: "genotype1",
      fatherId: 1,
      motherId: 2,
      cageID: 0,
    },
    {
      identifier: 5,
      earPunch: "L",
      strain: "strain1",
      sex: "M",
      dateOfBirth: "01/01/24",
      genotype: "genotype1",
      fatherId: 1,
      motherId: 2,
      cageID: 0,
    },
    {
      identifier: 6,
      earPunch: "RL",
      strain: "strain1",
      sex: "M",
      dateOfBirth: "01/01/24",
      genotype: "genotype1",
      fatherId: 1,
      motherId: 2,
      cageID: 0,
    },
    {
      identifier: 7,
      earPunch: "RR",
      strain: "strain1",
      sex: "M",
      dateOfBirth: "01/01/24",
      genotype: "genotype1",
      fatherId: 1,
      motherId: 2,
      cageID: 0,
    },
    {
      identifier: 8,
      earPunch: "N",
      strain: "strain2",
      sex: "F",
      dateOfBirth: "01/01/24",
      genotype: "genotype2",
      fatherId: 10,
      motherId: 20,
      cageID: 1,
    },
    {
      identifier: 9,
      earPunch: "R",
      strain: "strain2",
      sex: "F",
      dateOfBirth: "01/01/24",
      genotype: "genotype2",
      fatherId: 10,
      motherId: 20,
      cageID: 1,
    },
    {
      identifier: 11,
      earPunch: "L",
      strain: "strain2",
      sex: "F",
      dateOfBirth: "01/01/24",
      genotype: "genotype2",
      fatherId: 10,
      motherId: 20,
      cageID: 1,
    },
    {
      identifier: 12,
      earPunch: "RL",
      strain: "strain2",
      sex: "F",
      dateOfBirth: "01/01/24",
      genotype: "genotype2",
      fatherId: 10,
      motherId: 20,
      cageID: 1,
    },
    {
      identifier: 13,
      earPunch: "RR",
      strain: "strain2",
      sex: "F",
      dateOfBirth: "01/01/24",
      genotype: "genotype2",
      fatherId: 10,
      motherId: 20,
      cageID: 1,
    },
    {
      identifier: 14,
      earPunch: "N",
      strain: "strain3",
      sex: "F",
      dateOfBirth: "01/01/24",
      genotype: "genotype2",
      fatherId: 10,
      motherId: 20,
      cageID: 2,
    },
    {
      identifier: 15,
      earPunch: "R",
      strain: "strain3",
      sex: "F",
      dateOfBirth: "01/01/24",
      genotype: "genotype2",
      fatherId: 10,
      motherId: 20,
      cageID: 2,
    },
    {
      identifier: 16,
      earPunch: "N",
      strain: "strain4",
      sex: "M",
      dateOfBirth: "01/01/24",
      genotype: "wild-type",
      fatherId: 10,
      motherId: 20,
      cageID: 2,
    },
    {
      identifier: 17,
      earPunch: "N",
      strain: "strain4",
      sex: "F",
      dateOfBirth: "01/01/24",
      genotype: "wild-type",
      fatherId: 40,
      motherId: 50,
      cageID: 3,
    },
    {
      identifier: 18,
      earPunch: "R",
      strain: "strain4",
      sex: "F",
      dateOfBirth: "01/01/24",
      genotype: "wild-type",
      fatherId: 40,
      motherId: 50,
      cageID: 3,
    },
    {
      identifier: 19,
      earPunch: "N",
      strain: "strain4",
      sex: "M",
      dateOfBirth: "01/01/24",
      genotype: "wild-type",
      fatherId: 40,
      motherId: 50,
      cageID: 3,
    },
  ],

  cages: [
    {
      name: "Stock Genotype1 males",
      location: "SPF Room 1",
      rack: "Rack 01",
      type: "Stock",
      diet: "Normal diet",
      enrichment: "Normal",
    },
    {
      name: "Stock Genotype2 females",
      location: "SPF Room 1",
      rack: "Rack 02",
      type: "Stock",
      diet: "Normal diet",
      enrichment: "Normal",
    },
    {
      name: "Breeding Genotype1",
      location: "SPF Room 2",
      rack: "Rack 01",
      type: "Breeding",
      diet: "Normal diet",
      enrichment: "Normal",
    },
    {
      name: "Breeding wild-type",
      location: "SPF Room 2",
      rack: "Rack 02",
      type: "Breeding",
      diet: "Normal diet",
      enrichment: "Normal",
    },
  ],
};

module.exports = seedData;
